<a href="https://colab.research.google.com/github/rolandkristo/llm/blob/main/preliminaries/quick_dl_torch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://cdn.githubraw.com/antndlcrx/oss_2024/main/images/dpir_oss.png?raw=true:,  width=70" alt="My Image" width=500>

# **Deep Learning and PyTorch**

## **1**.&nbsp; **Deep Learning**

**Deep learning** is a subfield of machine learning that uses **neural networks with many layers to automatically learn patterns from large amounts of data**. These models are inspired by the structure of the human brain and can learn to recognize complex patterns in text, images, audio, and more.

<img src="https://cdn.githubraw.com/antndlcrx/oss_2024/main/images/dl_from_pytorch_book.png?raw=true:,  width=70" alt="My Image" width=700>

[Image Source](https://isip.piconepress.com/courses/temple/ece_4822/resources/books/Deep-Learning-with-PyTorch.pdf)

### **Backpropagation**

The **learning process is driven by** an algorithm called **backpropagation**, which adjusts the model's internal parameters (weights) based on how far off its predictions are from the actual outcomes. **This is done by computing gradients** — how much each parameter contributed to the error — and updating the parameters to improve performance.

<img src="https://cdn.githubraw.com/antndlcrx/oss_2024/main/images/backprop_torch_book.png?raw=true:,  width=70" alt="My Image" width=700>

[Image Source](https://isip.piconepress.com/courses/temple/ece_4822/resources/books/Deep-Learning-with-PyTorch.pdf)

Frameworks like [**PyTorch**](https://pytorch.org/tutorials/beginner/basics/intro.html) make this process efficient and intuitive by automatically handling gradient computation and parameter updates through tools like autograd and optimizers.

> 📖 For a deep (no pun intended) dive, check-out these resources:
- [**Deep Learning with PyTorch Book by Stevens, Antiga, Viehmann**](https://isip.piconepress.com/courses/temple/ece_4822/resources/books/Deep-Learning-with-PyTorch.pdf)
- [**Deep Learning by Goodfellow, Bengio, Aaron Courville**](https://www.deeplearningbook.org/).

## **2**.&nbsp; **PyTorch**

🔧 **Introduction to PyTorch, Tensors, and Autograd**

**PyTorch** is a popular deep learning framework that combines flexibility and performance, widely used for machine learning and scientific computing. At its core is the concept of the **tensor** — a generalization of arrays or matrices. Tensors are **multidimensional arrays** that can run on either the CPU or GPU, making them ideal for high-performance computations.

A **PyTorch tensor** is like a NumPy array, but with **built-in support for automatic differentiation and GPU acceleration**. You can perform arithmetic, reshape operations, and apply complex functions, all while tracking the computational graph for gradients.

This tracking is handled by **autograd**, PyTorch's automatic differentiation engine. When you perform operations on tensors with `requires_grad=True`, PyTorch builds a computation graph behind the scenes. Then, by calling `.backward()`, it automatically computes the **gradients** of all involved tensors — which is essential for optimizing model parameters during training.

This combination of **tensors + autograd** enables PyTorch to support deep learning workflows with concise, readable code.

### 📦 **PyTorch Tensors: Attributes and Methods**

In PyTorch, a [**tensor**](https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html) is the primary data structure — like a NumPy array, but with support for automatic differentiation and GPU acceleration. Understanding a few key **tensor attributes** and **methods** will help you debug, reshape, and manipulate data effectively.

### 🔍 Common Tensor Attributes

| Attribute         | Description                            | Example Output             |
|------------------|----------------------------------------|----------------------------|
| `tensor.shape`   | The size of each dimension              | `torch.Size([3, 2])`       |
| `tensor.dtype`   | The data type (e.g., `float32`, `int64`) | `torch.float32`            |
| `tensor.device`  | The device the tensor is on (CPU/GPU)   | `cpu` or `cuda:0`          |
| `tensor.requires_grad` | Tracks if autograd will compute gradients | `True` or `False`      |

### 🛠️ Common Tensor Methods

| Method              | Purpose                                 |
|---------------------|-----------------------------------------|
| `tensor.view()`     | Reshapes the tensor (like `.reshape()`) |
| `tensor.unsqueeze()`| Adds a dimension (e.g., for batching)   |
| `tensor.squeeze()`  | Removes dimensions of size 1            |
| `tensor.item()`     | Extracts a Python number from a 1-element tensor |
| `tensor.detach()`   | Returns a new tensor detached from the computation graph |
| `tensor.clone()`    | Creates a copy of the tensor            |

---

### 🧠 **Main PyTorch Modules**

PyTorch is modular and offers a rich ecosystem for building and training deep learning models. Here are the most important submodules you'll use frequently:

### 🔧 `torch.nn`
This is the [**neural network module**](https://pytorch.org/docs/stable/nn.html), used to build models by combining layers like `nn.Linear`, `nn.Conv2d`, `nn.ReLU`, etc. You typically subclass `nn.Module` to define custom models.

```python
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(10, 5),
    nn.ReLU(),
    nn.Linear(5, 1)
)
```

### 🎯 `torch.nn.functional` (aka `F`)
This module provides **stateless versions** of layers and activation functions. You use `F.relu(x)` or `F.cross_entropy()` when you want more control over operations inside your custom model. See more [here](https://pytorch.org/docs/stable/nn.functional.html).

```python
import torch.nn.functional as F

x = torch.randn(3, 5)
output = F.relu(x)
```

### 📉 `torch.optim`
This [module](https://pytorch.org/docs/stable/optim.html) includes **optimizers** like SGD, Adam, etc., which are used to update model parameters during training.

```python
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
```

### 📦 `torch.utils.data`
[`torch.utils.data`](https://pytorch.org/docs/stable/data.html) provides tools for handling data, such as `Dataset` and `DataLoader`. These help manage large datasets and batch training.

```python
from torch.utils.data import DataLoader, TensorDataset

dataset = TensorDataset(x, y)
loader = DataLoader(dataset, batch_size=32, shuffle=True)
```


### **Mini Example: Bivariate Linear Regression**

In [1]:
import torch

In [ ]:
n_vars = 5

tensor([0.2576]) 
 tensor([0.3470, 0.0240, 0.7797, 0.1519, 0.7513])


Epoch 0: loss 0.12258274108171463
Epoch 1000: loss 0.00927831046283245
Epoch 2000: loss 0.0010254544904455543
Epoch 3000: loss 0.00012447939661797136
Epoch 4000: loss 1.6749381757108495e-05


In [ ]:
#@title hide

# data
torch.manual_seed(42)

torch.rand(3)

n_features = 5

X = torch.rand((50, n_features))
a = torch.rand(1)
b = torch.rand(n_features)

y = a + X * b

print(a, "\n", b)

# implement

w = torch.rand(n_features, requires_grad=True)
b = torch.rand(1, requires_grad=True)

epochs = 5000

# loss_fn = torch.nn.MSELoss
optimizer = torch.optim.SGD(params=[w, b], lr=0.01)

# p = p - lr * grad

for e in range(epochs):

    y_pred = w * X + b
    loss = torch.mean((y_pred - y)**2)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    if e % 1000 == 0:
        print(f"Epoch {e}: loss {loss}")

tensor([0.2576]) 
 tensor([0.3470, 0.0240, 0.7797, 0.1519, 0.7513])
Epoch 0: loss 0.346267431974411
Epoch 1000: loss 0.011155854910612106
Epoch 2000: loss 0.001558643183670938
Epoch 3000: loss 0.00041113299084827304
Epoch 4000: loss 0.0001776695135049522


In [ ]:
import matplotlib.pyplot as plt

# Get the final predictions
y_pred = X * w + b

# Detach tensors from the computational graph for plotting
y_pred_np = y_pred.detach().numpy()
y_np = y.detach().numpy()

# Create the scatter plot
plt.figure(figsize=(8, 6))
plt.scatter(y_np, y_pred_np)
plt.xlabel("Actual (y)")
plt.ylabel("Predicted (y_pred)")
plt.title("Scatter Plot of Actual vs. Predicted Values")
plt.grid(True)
plt.show()

In [ ]:
# demo @ if necessary
torch.manual_seed(42)

x = torch.rand((2))
print(x, "\n"*2)

y = torch.rand((2, 10))
print(y, "\n"*2)

print(x @ y, "\n"*2)

x[0] * y[0, 0] + x[1] * y[1, 0] # for 2d

tensor([0.8823, 0.9150]) 


tensor([[0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408, 0.1332, 0.9346,
         0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696,
         0.4414]]) 


tensor([1.1333, 1.3658, 1.0226, 0.9231, 1.0365, 1.2253, 1.0739, 0.6916, 1.0713,
        0.9275]) 




tensor(1.1333)